import PDFDocument from 'pdfkit';
import type { LetterConfig, LetterGeneration } from '../schemas/letters.js';

export type PDFSection = LetterGeneration['sections']['header'];

const BUILTIN_FONTS = {
	Courier: 'Courier',
	Helvetica: 'Helvetica',
	'Times-Roman': 'Times-Roman'
} as const satisfies Record<LetterConfig['font'], string>;

/**
 * Renders a generated letter (no substitution tags left) to a PDF Buffer.
 * Honors font, size, colors, line height, page size, margins, and per-section
 * alignment from the letter config. `textDirection` is not applied: pdfkit
 * has no bidi direction option.
 */
export async function renderLetterPdf(generated: LetterGeneration): Promise<Buffer> {
	const { config, sections } = generated;
	return new Promise<Buffer>((resolve, reject) => {
		const doc = new PDFDocument({
			size: config.pageSize === 'LETTER' ? 'LETTER' : 'A4',
			layout: 'portrait',
			margins: {
				top: config.marginTop,
				bottom: config.marginBottom,
				left: config.marginLeft,
				right: config.marginRight
			},
			info: {
				Title: 'Cover letter',
				Subject: 'Cover letter generated by Cover Voice',
				Keywords: 'Cover Letter'
			}
		});
		const chunks: Buffer[] = [];
		doc.on('data', (chunk: Buffer) => chunks.push(chunk));
		doc.on('error', reject);
		doc.on('end', () => resolve(Buffer.concat(chunks)));

		// Page background.
		const { width, height } = doc.page;
		doc.save().rect(0, 0, width, height).fillColor(config.backgroundColor).fill().restore();

		doc.fillColor(config.fontColor);
		doc.font(BUILTIN_FONTS[config.font]);
		doc.fontSize(config.fontSize);
		const lineGap = Math.max(0, (config.lineHeight - 1) * config.fontSize);

		let first = true;
		for (const section of [sections.header, sections.body, sections.footer]) {
			if (section.text === null || section.text === '') continue;
			if (!first) doc.moveDown();
			first = false;
			doc.text(section.text, { align: section.align, lineGap });
		}
		doc.end();
	});
}
